language: c

env:
  matrix:
    - PYTHON_VERSION=2.7 UNITPKG=false
    - PYTHON_VERSION=3.3 UNITPKG=false
    - PYTHON_VERSION=3.4 UNITPKG=false
    - PYTHON_VERSION=3.5 UNITPKG=false
    - PYTHON_VERSION=2.7 UNITPKG=true
    - PYTHON_VERSION=3.4 UNITPKG=true
    - PYTHON_VERSION=3.5 UNITPKG=true
  global:
    - CONDA_DEPENDENCIES="pytest numpy"
    - PIP_DEPENDENCIES="coveralls pytest-cov traitlets"

install:
    - if [[ $UNITPKG == true ]]; then export CONDA_DEPENDENCIES="astropy "$CONDA_DEPENDENCIES; fi
    - if [[ $UNITPKG == true ]]; then export PIP_DEPENDENCIES="quantities pint "$PIP_DEPENDENCIES; fi
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - py.test --cov numtraits.py

after_success:
  - coveralls
